import ThemeColor from '@Theme/Colors';

const LightTheme = {
  type: 'light',
  keyboardAppearance: 'light',
  themeColor: ThemeColor.primary,
  background: ThemeColor.white,
  shadowColor: ThemeColor.black,
  card: ThemeColor.lighter,
  text: ThemeColor.gray6,
  lightText: ThemeColor.gray3,
  border: ThemeColor.lightGray4,
  tint: ThemeColor.white,
  gradient: ThemeColor.gradient,
  tab: ThemeColor.white,
  statusBar: 'dark-content',
  red: 'red',
  transparent: 'transparent',
  textBorder: ThemeColor.lightGray4,
  gray: ThemeColor.gray,
  overlay: ThemeColor.overlay,
  darkYellow: ThemeColor.darkYellow,
  lightYellow: ThemeColor.lightYellow,
  lightGrayText: ThemeColor.gray7,
  lightThemeColor: ThemeColor.primary,
  darkThemeColor: ThemeColor.primaryDark,
  lightGrayBack: ThemeColor.lightGray7,
  subText: ThemeColor.gray8,
  lightOverlay: ThemeColor.lightOverlay,
  blackMat: ThemeColor.blackMat,
  tabIconFill: ThemeColor.darkYellow2,
  fillHeart: ThemeColor.lightRed,
  lightSlider: ThemeColor.lightGray8,
  reviewText: ThemeColor.gray9,
  dotsBackground: ThemeColor.lightGray5,
};

export default LightTheme;
