const en = {
  SETTINGS: 'Settings',
  LANGUAGE: 'LANGUAGE',
  THEME: 'THEME',
  DARK_MODE: 'Dark Mode',
  SIGN_IN: 'Log in',
  LOG_OUT: 'Log out',
  SEARCH_PLACEHOLDER: 'Search Products or store',
  USER_NAME: 'Hey, Ram',
  DELIVERY_TO: 'Delivery to',
  WITH_IN: 'With in',
  RECOMMENDED: 'Recommended',
  EMPTY_RECOMMENDED_TEXT: 'No recommended products found',
  EMPTY_FAVORITES_TEXT: 'No favorite products found',
  FAVORITES: 'Favorites',
  SOMETHING_WENT_WRONG: 'Something went wrong',
  ADD_TO_CART: 'Add to cart',
  ADDED_TO_CART: 'Added to cart',
  BUY_NOW: 'Buy now',
  DETAILS: 'Details',
  REVIEW: '110 Reviews',
  SHOPPING_CART: 'Shopping Cart',
  EMPTY_CART_TEXT: 'Sorry, your cart is empty!',
  PROCEED_TO_CHECKOUT: 'Proceed to checkout',
  SUB_TOTAL: 'Subtotal',
  DELIVERY_CHARGES: 'Delivery charges',
  TOTAL: 'Total',
  PRODUCT_ADDED_TO_CART: 'Product added to cart',
  PRODUCT_REMOVED_FROM_CART: 'Product removed from cart',
};

export { en };
