export const GET_RECOMMENDED_PRODUCTS = 'GET_RECOMMENDED_PRODUCTS';
export const SET_RECOMMENDED_PRODUCTS = 'SET_RECOMMENDED_PRODUCTS';

export const GET_CURRENT_PRODUCT = 'GET_CURRENT_PRODUCT';
export const SET_CURRENT_PRODUCT = 'SET_CURRENT_PRODUCT';
